package com.twitter.botmaker.compiler;

public enum ActionLevel {
  UNDOCUMENTED,
  RESERVED_FOR_DERIVED_FEATURE,
  NO_ACTION,
  PROD_TANGIBLE_IMPACT_ACTION,
  PROD_AGENT_WORKFLOW_ACTION,
  PROD_OTHER_ACTION,
  RESPONSE_CODE_NO_CHANGE_ACTION,
  RESPONSE_CODE_CHANGE_BEHAVIOR_ACTION
}
