create_thrift_libraries(
    base_name = "rule",
    generate_languages = [
        "go",
        "java",
        "lua",
        "python",
        "ruby",
        "scala",
        "strato",
    ],
    platform = "java8",
    provides_java_name = "rule-thrift-java",
    provides_python_name = "rule-thrift-python",
    provides_scala_name = "rule-thrift-scala",
    sources = [
        "rule.thrift",
    ],
    tags = ["bazel-compatible"],
)
