scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "decider",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/authorization/server",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/client",
        "finagle/finagle-core/src/main",
        "finagle/finagle-http/src/main/scala",
        "finagle/finagle-stats",
        "finagle/finagle-thriftmux",
        "finatra-internal/decider/src/main/scala",
        "finatra-internal/mtls-thriftmux/src/main/scala",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "finatra/inject/inject-thrift-client",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift:controller",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/exceptions",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/filters",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/modules",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/response",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/routing",
        "media-understanding/common/src/main/scala/com/twitter/media_understanding/common/filters",
        "media-understanding/common/src/main/scala/com/twitter/media_understanding/common/modules",
        "media-understanding/media-model-proxy/src/main/resources",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/controllers",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/model_descriptors",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/modules",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/services",
        "media-understanding/media-model-proxy/src/main/thrift:thrift-scala",
        "thrift-web-forms/src/main/scala/com/twitter/thriftwebforms/view",
        "twitter-server-internal",
        "twitter-server-internal/src/main/scala",
        "twitter-server/server/src/main/scala",
        "util/util-app",
        "util/util-core:scala",
        "util/util-logging/src/main/scala",
        "util/util-slf4j-api/src/main/scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
