scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "cortex-common/services/src/main/scala/com/twitter/cortex_common/services/client",
        "cortex-common/services/src/main/scala/com/twitter/cortex_common/services/monitoring",
        "cortex-common/services/src/main/scala/com/twitter/cortex_common/services/repository",
        "cortex-common/services/src/main/scala/com/twitter/cortex_common/services/service_adaptor",
        "cortex-common/util/src/main/scala/com/twitter/cortex/common/util",
        "cortex-core/thrift/src/main/thrift:thrift-scala",
        "cortex-deepbird/thrift/src/main/thrift:thrift-scala",
        "decider",
        "finagle/finagle-core/src/main",
        "finagle/finagle-stats",
        "finagle/finagle-thriftmux",
        "finatra/inject/inject-core/src/main/scala",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/clients",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/config",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/exception",
        "media-understanding/media-model-proxy/src/main/thrift:thrift-scala",
        "src/thrift/com/twitter/ml/api:data-scala",
        "util/util-core:scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
