# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 X.AI Corp.
[project]
name = "xai-recsys-engine"
version = "0.2.0"

[build-system]
build-backend = "maturin"
requires = ["maturin>=1.7,<2.0"]

[tool.maturin]
bindings = "pyo3"
features = ["pyo3/extension-module"]
module-name = "xai_recsys_engine"
profile = "release"

[tool.uv]
cache-keys = [
  { file = "**" },
  { file = "../../../crates/common/xai-recsys/**" },
  { file = "../../../crates/serving/xai-recsys-mm-server/**" },
  { file = "../../../crates/serving/xai-recsys-proto/**" },
  { file = "../../../crates/serving/xai-recsys-server/**" },
]
