scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "decider",
        "finatra-internal/decider/src/main/scala",
        "media-understanding/common/src/main/scala/com/twitter/media_understanding/common/config",
        "media-understanding/media-model-proxy/src/main/resources",
        "media-understanding/media-model-proxy/src/main/thrift:thrift-scala",
        "util/util-core:scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
