scala_library(
    name = "server",
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/com/google/inject/extensions:guice-assistedinject",
        "3rdparty/jvm/io/netty:netty4-tcnative-boringssl-static",
        "3rdparty/jvm/javax/inject:javax.inject",
        "3rdparty/jvm/net/codingwell:scala-guice",
        "3rdparty/jvm/org/apache/commons:commons-lang3",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "botmaker/botmaker_app/src/main/scala/com/twitter/botmaker/app/module",
        "botmaker/botmaker_loader/src/main/scala/com/twitter/botmaker/loader:lib",
        "botmaker/src/java/com/twitter/botmaker",
        "botmaker/src/scala/com/twitter/botmaker",
        "botmaker/src/thrift/com/twitter/botmaker/app:app-java",
        "botmaker/src/thrift/com/twitter/botmaker/app:app-scala",
        "botmaker/src/thrift/com/twitter/botmaker/rule:rule-java",
        "botmaker/src/thrift/com/twitter/botmaker/rule:rule-scala",
        "botmaker/src/thrift/com/twitter/botmaker/runtime:runtime-java",
        "botmaker/src/thrift/com/twitter/botmaker/runtime:runtime-scala",
        "configbus/client/src/main/scala/com/twitter/configbus/client",
        "configbus/client/src/main/scala/com/twitter/configbus/client/api",
        "decider/src/main/scala",
        "eventbus/client/src/main/scala/com/twitter/eventbus/client",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/authentication",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/authorization",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/client",
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/server",
        "finagle/finagle-core/src/main",
        "finagle/finagle-http/src/main/scala",
        "finagle/finagle-memcached/src/main/scala",
        "finagle/finagle-mux/src/main/scala",
        "finagle/finagle-mysql/src/main/scala",
        "finagle/finagle-thrift/src/main/java",
        "finagle/finagle-thrift/src/main/scala",
        "finagle/finagle-thriftmux/src/main/scala",
        "finatra-internal/decider/src/main/scala",
        "finatra-internal/mtls-thriftmux/src/main/scala",
        "finatra/http-client/src/main/scala",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-modules/src/main/scala",
        "finatra/inject/inject-modules/src/main/scala/com/twitter/inject/modules",
        "finatra/inject/inject-request-scope/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "finatra/inject/inject-thrift-client",
        "finatra/inject/inject-utils/src/main/scala",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift:controller",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/exceptions",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/filters",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/modules",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/response",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/routing",
        "loglens/loglens-logging/src/main/scala",
        "src/java/com/twitter/common/io",
        "src/thrift/com/twitter/relevance/feature_store:feature_store-java",
        "src/thrift/com/twitter/relevance/feature_store:feature_store-scala",
        "thrift-web-forms/src/main/scala/com/twitter/thriftwebforms/view",
        "twitter-server-internal/naming/src/main/scala",
        "twitter-server-internal/src/main/scala",
        "twitter-server/server/src/main/scala",
    ],
    platform = "java8",
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
)
