scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "finatra-internal/decider/src/main/scala",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "finatra/inject/inject-thrift-client",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift:controller",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/exceptions",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/filters",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/modules",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/response",
        "finatra/thrift/src/main/scala/com/twitter/finatra/thrift/routing",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/services",
        "media-understanding/media-model-proxy/src/main/scala/com/twitter/media_understanding/model_proxy/util",
        "media-understanding/media-model-proxy/src/main/thrift:thrift-scala",
        "util/util-core:scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
