scala_library(
    dependencies = [
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "hub/pmi/src/main/scala/com/twitter/hub/pmi",
    ],
    platform = "java8",
    sources = ["*.scala"],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
