scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/org/uaparser:uap-scala",
        "botmaker/src/scala/com/twitter/botmaker",
        "common-internal/analytics/twitter-client-user-agent-parser/src/main/scala",
    ],
    platform = "java8",
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
)
