scala_library(
    name = "lib",
    dependencies = [
        "botmaker/src/scala/com/twitter/botmaker",
        "configbus/client/src/main/scala/com/twitter/configbus/client",
    ],
    platform = "java8",
    sources = ["**/*.scala"],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
