scala_library(
    name = "util",
    dependencies = [
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "3rdparty/src/jvm/com/twitter/scalding:thrift-macros",
        "agatha/src/main/thrift/com/twitter/agatha:agatha-scala",
        "healthde/src/main/scala/com/twitter/healthde/suspension_events:suspension_events-scala",
        "src/java/com/twitter/ml/api/constant",
        "src/scala/com/twitter/ml/api:api-base",
        "src/scala/com/twitter/ml/api/util",
        "src/scala/com/twitter/scalding_internal/dalv2",
        "usersource/snapshot/src/main/scala/com/twitter/usersource/snapshot/combined:usersource-scala",
    ],
    platform = "java8",
    sources = [
        "GetActiveUsers.scala",
        "GetSuspendedUsers.scala",
        "PredictionsToDataSetPipe.scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)

scala_library(
    name = "features-to-label",
    dependencies = [
        ":util",
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "3rdparty/src/jvm/com/twitter/scalding:thrift-macros",
        "agatha/src/main/thrift/com/twitter/agatha:agatha-scala",
        "src/scala/com/twitter/scalding_internal/dalv2",
        "usersource/snapshot/src/main/scala/com/twitter/usersource/snapshot/combined:usersource-scala",
    ],
    platform = "java8",
    sources = ["FeaturesToLabels.scala"],
    strict_deps = False,
    tags = ["bazel-compatible"],
)
