scala_library(
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/com/googlecode/json-simple",
    ],
    platform = "java8",
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
)
