create_thrift_libraries(
    base_name = "agatha",
    dependency_roots = [
    ],
    generate_languages = [
        "java",
        "scala",
    ],
    platform = "java8",
    provides_java_name = "agatha-java",
    provides_scala_name = "agatha-scala",
    sources = ["*.thrift"],
    tags = ["bazel-compatible"],
)
