resources(
    sources = [
        "*.jpg",
        "*.xml",
        "*.yml",
        "META-INF/services/*",
        "com/twitter/tunables/cortex_media_annotator/*.json",
        "config/*.yml",
    ],
)
