python37_binary(
    name = "media_embeddings_batch_inference",
    dependencies = [
        "3rdparty/python/_closures/media-understanding/clip/src/main/python/twitter/clip/notebooks:media_embeddings_batch_inference",
        "media-understanding/common/src/main/python/com/twitter/media_understanding/common/batch_inference",
        "src/python/twitter/ml/common/apache_beam",
    ],
    entry_point = "",
)
