java_library(
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/org/antlr:antlr-3.5",
        "3rdparty/jvm/org/apache/commons:commons-lang3",
        "3rdparty/jvm/org/apache/commons:commons-text",
        "3rdparty/jvm/org/reflections",
        "botmaker/src/antlr/com/twitter/botmaker:botmaker-antlr",
        "scrooge/scrooge-core/src/main/scala",
        "util/util-function/src/main/java",
        "util/util-stats/src/main/scala",
    ],
    platform = "java8",
    sources = ["**/*.java"],
    tags = ["bazel-compatible"],
)
