scala_library(
    name = "active_user_features_job",
    dependencies = [
        ":active_user_features-scala",
        ":feature_extraction_template",
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "agatha/src/main/scala/com/twitter/agatha/scalding/data/loaders:all_loaders",
        "agatha/src/main/scala/com/twitter/agatha/scalding/util",
        "hub/agatha/src/main/thrift/com/twitter/hub/agatha:agatha-scala",
        "src/scala/com/twitter/scalding_internal/dalv2",
    ],
    platform = "java8",
    sources = [
        "ActiveUserFeaturesJob.scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)

create_datasets(
    base_name = "active_user_features",
    java_dependencies = [
        "hub/agatha/src/main/thrift/com/twitter/hub/agatha:agatha-java",
    ],
    java_schema = "com.twitter.hub.agatha.thriftjava.UserFeature",
    platform = "java8",
    role = "agatha",
    scala_dependencies = [
        "hub/agatha/src/main/thrift/com/twitter/hub/agatha:agatha-scala",
    ],
    scala_schema = "com.twitter.hub.agatha.thriftscala.UserFeature",
    segment_type = "snapshot",
    tags = ["bazel-compatible"],
)

scala_library(
    name = "feature_extraction_template",
    dependencies = [
        ":data_loader",
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "hub/agatha/src/main/thrift/com/twitter/hub/agatha:agatha-scala",
        "src/scala/com/twitter/mediascience/scalding/extensions",
        "src/scala/com/twitter/scalding_internal/job",
        "src/scala/com/twitter/scalding_internal/job/analytics_batch",
    ],
    platform = "java8",
    sources = [
        "FeatureExtractionTemplate.scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)

scala_library(
    name = "data_loader",
    dependencies = [
        "3rdparty/src/jvm/com/twitter/scalding:core",
        "3rdparty/src/jvm/com/twitter/scalding:serialization",
        "hub/agatha/src/main/thrift/com/twitter/hub/agatha:agatha-scala",
        "src/scala/com/twitter/common_internal/analytics/artificial_user_filter",
    ],
    platform = "java8",
    sources = [
        "DataLoader.scala",
        "DataLoaderUtil.scala",
    ],
    strict_deps = False,
    tags = ["bazel-compatible"],
)

hadoop_binary(
    name = "active-user-features-bin",
    dependencies = [":active_user_features_job"],
    main = "com.twitter.agatha.scalding.data.ScheduledActiveUserFeaturesJob",
    platform = "java8",
    runtime_platform = "java8",
    tags = [
        "bazel-compatible",
        "bazel-compatible:migrated",
        "bazel-only",
    ],
)

scalding_job(
    name = "active_user_features_deploy",
    args = ["--tz UTC --batchFirstTime 2020-10-31 --increment 1 --batchDesc ActiveUserFeatures"],
    config = [
        ("hadoop.combine-input", "true"),
        ("hadoop.data-per-reducer", "536870912"),
        ("hadoop.map.jvm.total-memory", "3072m"),
        ("hadoop.queue", "agatha.tier2"),
        ("hadoop.reduce.jvm.total-memory", "3072m"),
        ("hadoop.split-size", "1073741824"),
        ("hadoop.submitter.jvm.total-memory", "5120m"),
    ],
    contact = "agatha-owners@twitter.com",
    cron = "0 * * * *",
    dependencies = [":active_user_features_job"],
    hadoop_cluster = "atla-proc",
    hadoop_properties = [
        ("scalding.reducer.estimator.max.estimated.reducers", "10000"),
        ("mapreduce.job.split.metainfo.maxsize", "-1"),
    ],
    main = "com.twitter.agatha.scalding.data.ScheduledActiveUserFeaturesJob",
    platform = "java8",
    role = "agatha",
    runtime_platform = "java8",
    tags = [
        "bazel-compatible:migrated",
        "bazel-only",
    ],
)
